### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by yinhuey19** [ngocongcan/ionic2-GoPREx#1]
HI,
May I know your's api coming from what website?

Thanks!

**Comment by ngocongcan** [comment]
Hi ,

I'm using two APIs which come from 
https://www.vietcombank.com.vn/exchangerates/ExrateXML.aspx
http://www.sjc.com.vn/xml/tygiavang.xml

Regards,
Can

**Comment by yinhuey19** [comment]
Hi Can,
Thanks for the reply.

May I ask that if I want to change the api link is to paste my api at the apiUrl right?
![111](https://cloud.githubusercontent.com/assets/27809080/26624025/37ab1ffc-4622-11e7-9bae-1955610163c2.JPG)

Thanks,
Best Regards,
Huey

**Comment by ngocongcan** [comment]
Yes, You can do it
